import { Metadata } from "next";
import { ArrowUpRight, BookOpen } from "lucide-react";

export const metadata: Metadata = {
  title: "Research | QuantaLabs",
  description: "Applied research on lattice-based cryptography, ZKPs, and PQC migration strategies.",
};

const PAPERS = [
  {
    id: "LCE-2026-01",
    title: "Learning with Correlated Errors: A New Lattice Hard Problem with Worst-Case Reductions and Public-Key Encryption",
    authors: "Kishore K",
    date: "MAY 2026",
    type: "PREPRINT",
    abstract: "We introduce Learning with Correlated Errors (LCE), a new lattice-based computational hardness assumption in which observed samples carry noise generated by a low-rank linear correlation structure. We prove worst-case hardness via reduction from Decision-LWE, a search-to-decision reduction, construct an IND-CPA-secure PKE scheme, and establish quantum resistance. LCE provides a new, independently motivated hardness foundation for post-quantum cryptography beyond LWE and LPN.",
    zenodoUrl: "https://zenodo.org/records/20361875",
    doi: "10.5281/zenodo.20361875",
  },
  {
    id: "QTO-2026-02",
    title: "Quantum Temporal Order: Structural Inevitability of Modular Flow and the Problem of Time",
    authors: "Kishore K",
    date: "MAR 2026",
    type: "PREPRINT",
    abstract: "We address the problem of time in quantum mechanics, showing that a canonical preferred temporal flow arises from within the algebraic structure of quantum mechanics without presupposing a Hamiltonian, a Schrödinger equation, or a background time parameter. Three results are established: Structural Inevitability, Cocycle Colimit, and Classical Recovery. This paper extends the Connes–Rovelli thermal time hypothesis and the Page–Wootters relational framework to a universal directed cocycle colimit.",
    zenodoUrl: "https://zenodo.org/records/18845465",
    doi: "10.5281/zenodo.18845465",
  },
  {
    id: "QNT-2026-03",
    title: "QUANTA: Engineering a Production-Ready Post-Quantum Blockchain with Falcon-512 Lattice Signatures",
    authors: "Kishore K",
    date: "FEB 2026",
    type: "TECHNICAL REPORT",
    abstract: "We present QUANTA, an open-source blockchain built exclusively on NIST-standardized post-quantum cryptography: Falcon-512 (FIPS 206) for transaction signatures and Kyber-1024 (ML-KEM, FIPS 203) for node-to-node key encapsulation. No classical primitive appears in the critical path. Describes protocol hardening, parallel block validation, integer-only consensus arithmetic, compressed storage, and a crypto-agility mechanism for future algorithm migration without a hard fork.",
    zenodoUrl: "https://zenodo.org/records/18753528",
    doi: "10.5281/zenodo.18753528",
  },
];

export default function ResearchPage() {
  return (
    <div className="bg-white min-h-screen pt-28 pb-24 text-black">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Page Header */}
        <div className="border border-gray-200 shadow-sm bg-white mb-12">
          <div className="grid grid-cols-1 lg:grid-cols-12">
            <div className="lg:col-span-8 p-10 md:p-16 border-b lg:border-b-0 lg:border-r border-black/10 bg-[#C4ED5F] relative">
              <div 
                className="absolute inset-0 opacity-30 pointer-events-none"
                style={{
                  backgroundImage: `linear-gradient(rgba(0,0,0,0.15) 1px, transparent 1px), linear-gradient(90deg, rgba(0,0,0,0.15) 1px, transparent 1px)`,
                  backgroundSize: "24px 24px"
                }}
              ></div>
              <div className="flex items-center gap-3 mb-6 relative z-10">
                <div className="w-2 h-2 bg-black"></div>
                <span className="font-mono text-[10px] tracking-[0.2em] text-black/60 uppercase font-bold">
                  Applied Research
                </span>
              </div>
              <h1 className="text-[3rem] md:text-[5rem] font-black tracking-tighter leading-[0.95] text-black relative z-10">
                Theory into<br/>production.
              </h1>
            </div>
            
            <div className="lg:col-span-4 p-10 flex flex-col justify-end bg-[#C4ED5F] relative overflow-hidden border-l border-black/10">
               <div 
                className="absolute inset-0 opacity-[0.15] pointer-events-none"
                style={{
                  backgroundImage: `linear-gradient(rgba(0,0,0,1) 1px, transparent 1px), linear-gradient(90deg, rgba(0,0,0,1) 1px, transparent 1px)`,
                  backgroundSize: "20px 20px"
                }}
              ></div>
              <span className="absolute top-8 right-8 text-[6rem] font-black text-black leading-none select-none">∑</span>
              <div className="relative z-10">
                <BookOpen className="w-8 h-8 text-black mb-6" strokeWidth={1.5} />
                <p className="text-sm text-black font-medium">
                  Our protocol engineering team regularly publishes findings on lattice-based cryptography, ZKPs, and secure migration strategies.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Papers List */}
        <div className="border border-gray-200 shadow-sm bg-white overflow-hidden">
          <div className="bg-gray-100 border-b border-gray-200 px-8 py-4 flex items-center justify-between">
            <span className="font-mono text-[10px] font-bold text-gray-500 uppercase tracking-widest">
              Index of Publications
            </span>
            <span className="font-mono text-[10px] font-bold text-gray-500 uppercase tracking-widest">
              {PAPERS.length} ITEMS
            </span>
          </div>

          <div className="flex flex-col">
            {PAPERS.map((paper, index) => (
              <div 
                key={paper.id} 
                className={`grid grid-cols-1 lg:grid-cols-12 hover:bg-gray-50 transition-colors ${
                  index !== PAPERS.length - 1 ? 'border-b border-gray-200' : ''
                }`}
              >
                
                {/* Meta Column */}
                <div className="lg:col-span-3 p-8 border-b lg:border-b-0 lg:border-r border-gray-200 flex flex-col justify-between bg-gray-50/30">
                  <div>
                    <div className="inline-block font-mono text-[10px] font-bold text-black bg-[#C4ED5F] px-2 py-1 uppercase tracking-widest mb-4">
                      {paper.id}
                    </div>
                    <div className="font-mono text-[9px] font-bold text-gray-400 uppercase tracking-widest mb-1">
                      {paper.date}
                    </div>
                    <div className="font-mono text-[9px] font-bold text-gray-600 uppercase tracking-widest border border-gray-200 px-1.5 py-0.5 inline-block bg-white mb-3">
                      {paper.type}
                    </div>
                    <div className="font-mono text-[9px] font-bold text-gray-400 uppercase tracking-widest">
                      DOI: {paper.doi}
                    </div>
                  </div>
                </div>

                {/* Content Column */}
                <div className="lg:col-span-7 p-8 md:p-10 flex flex-col justify-center">
                  <h2 className="text-xl md:text-2xl font-bold text-black mb-3">
                    {paper.title}
                  </h2>
                  <div className="font-mono text-xs text-gray-500 font-bold uppercase tracking-widest mb-6">
                    {paper.authors}
                  </div>
                  <p className="text-sm text-gray-600 font-medium leading-relaxed max-w-3xl">
                    {paper.abstract}
                  </p>
                </div>

                {/* Actions Column */}
                <div className="lg:col-span-2 p-6 border-t lg:border-t-0 lg:border-l border-gray-200 flex flex-row lg:flex-col items-center justify-center gap-4 bg-white">
                  <a 
                    href={paper.zenodoUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex flex-col items-center justify-center gap-2 p-4 bg-[#C4ED5F] hover:bg-black hover:text-white transition-colors w-full text-black"
                  >
                    <ArrowUpRight className="w-5 h-5" />
                    <span className="font-mono text-[9px] font-bold uppercase tracking-widest text-center">View on Zenodo</span>
                  </a>
                </div>

              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
