// CHANGED: Redesigned for Deep Tech Light Mode aesthetic.
// DATE: 2026-08-07 | VERSION: 4.0
import { Metadata } from "next";
import { ArrowUpRight } from "lucide-react";

export const metadata: Metadata = {
  title: "Research | QuantaLabs",
  description:
    "Applied research on lattice-based cryptography, ZKPs, and PQC migration strategies.",
};

const PAPERS = [
  {
    id: "LCE-2026-01",
    title:
      "Learning with Correlated Errors: A New Lattice Hard Problem with Worst-Case Reductions and Public-Key Encryption",
    authors: "Kishore K",
    date: "MAY 2026",
    type: "PREPRINT",
    abstract:
      "We introduce Learning with Correlated Errors (LCE), a new lattice-based computational hardness assumption in which observed samples carry noise generated by a low-rank linear correlation structure. We prove worst-case hardness via reduction from Decision-LWE, a search-to-decision reduction, construct an IND-CPA-secure PKE scheme, and establish quantum resistance. LCE provides a new, independently motivated hardness foundation for post-quantum cryptography beyond LWE and LPN.",
    zenodoUrl: "https://zenodo.org/records/20361875",
    doi: "10.5281/zenodo.20361875",
  },
  {
    id: "QTO-2026-02",
    title:
      "Quantum Temporal Order: Structural Inevitability of Modular Flow and the Problem of Time",
    authors: "Kishore K",
    date: "MAR 2026",
    type: "PREPRINT",
    abstract:
      "We address the problem of time in quantum mechanics, showing that a canonical preferred temporal flow arises from within the algebraic structure of quantum mechanics without presupposing a Hamiltonian, a Schrödinger equation, or a background time parameter. Three results are established: Structural Inevitability, Cocycle Colimit, and Classical Recovery. This paper extends the Connes–Rovelli thermal time hypothesis and the Page–Wootters relational framework to a universal directed cocycle colimit.",
    zenodoUrl: "https://zenodo.org/records/18845465",
    doi: "10.5281/zenodo.18845465",
  },
  {
    id: "QNT-2026-03",
    title:
      "QUANTA: Engineering a Production-Ready Post-Quantum Blockchain with Falcon-512 Lattice Signatures",
    authors: "Kishore K",
    date: "FEB 2026",
    type: "TECHNICAL REPORT",
    abstract:
      "We present QUANTA, an open-source blockchain built exclusively on NIST-standardized post-quantum cryptography: Falcon-512 (FIPS 206) for transaction signatures and Kyber-1024 (ML-KEM, FIPS 203) for node-to-node key encapsulation. No classical primitive appears in the critical path. Describes protocol hardening, parallel block validation, integer-only consensus arithmetic, compressed storage, and a crypto-agility mechanism for future algorithm migration without a hard fork.",
    zenodoUrl: "https://zenodo.org/records/18753528",
    doi: "10.5281/zenodo.18753528",
  },
];

export default function ResearchPage() {
  return (
    <div className="bg-transparent min-h-screen pt-32 pb-24 text-[#141413] font-sans selection:bg-[#C04A2B] selection:text-white">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Page Header */}
        <div className="mb-20 pb-12 border-b border-gray-200">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-white border border-gray-200 mb-8 shadow-sm">
            <span className="w-1.5 h-1.5 bg-[#C04A2B]"></span>
            <span className="text-[10px] tracking-[0.2em] text-gray-500 uppercase font-mono font-medium">Applied Research</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-display font-medium tracking-tight text-[#141413] leading-[1.05]">
            Theory into <br/><span className="text-gray-400">production.</span>
          </h1>
          <p className="mt-8 text-lg text-gray-600 max-w-2xl font-normal leading-relaxed">
            Our protocol engineering team regularly publishes findings on lattice-based cryptography, ZKPs, and secure migration strategies for the quantum era.
          </p>
        </div>

        {/* Papers List */}
        <div className="flex flex-col gap-12">
          {PAPERS.map((paper) => (
            <div key={paper.id} className="group relative bg-white border border-[#C04A2B] p-8 transition-colors shadow-sm overflow-hidden">
              <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:16px_16px] pointer-events-none"></div>
              <div className="absolute top-0 right-0 w-1 h-full bg-[#C04A2B] opacity-0 group-hover:opacity-100 transition-opacity"></div>
              <div className="relative z-10">
              
              <div className="flex flex-wrap gap-3 mb-6 relative z-10">
                <span className="font-mono text-[10px] font-medium text-white bg-[#C04A2B] px-2 py-1 uppercase tracking-widest">
                  {paper.id}
                </span>
                <span className="font-mono text-[10px] font-medium text-gray-500 bg-white border border-gray-200 px-2 py-1 uppercase tracking-widest">
                  {paper.date}
                </span>
                <span className="font-mono text-[10px] font-medium text-gray-500 bg-white border border-gray-200 px-2 py-1 uppercase tracking-widest">
                  {paper.type}
                </span>
              </div>

              <h2 className="text-2xl font-display font-medium text-[#141413] mb-2 tracking-tight relative z-10">
                {paper.title}
              </h2>
              <div className="font-mono text-xs text-gray-500 uppercase tracking-widest mb-6 relative z-10">
                Authors: {paper.authors}
              </div>
              
              <p className="text-sm text-gray-600 font-normal leading-relaxed max-w-3xl mb-8 relative z-10">
                {paper.abstract}
              </p>

              <div className="flex items-center gap-4 border-t border-gray-200 pt-6 relative z-10">
                <a
                  href={paper.zenodoUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-[#C04A2B] text-white font-mono text-xs uppercase tracking-widest hover:bg-[#141413] transition-all shadow-sm"
                >
                  View on Zenodo <ArrowUpRight className="w-4 h-4" />
                </a>
                <span className="font-mono text-[10px] text-gray-400 relative z-10">
                  DOI: {paper.doi}
                </span>
              </div>
            </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
